# Generated by Django 2.2.3 on 2020-03-24 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SEE', 'SEE'), ('Plus2', 'Plus2'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=15)),
                ('faculty', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YearOrSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV')], max_length=15)),
                ('sem', models.CharField(blank=True, choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V'), ('Sixth', 'VI'), ('Seventh', 'VII'), ('Eighth', 'VIII')], max_length=30, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=125)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.YearOrSemester')),
            ],
        ),
    ]
