# Generated by Django 3.0.4 on 2020-03-31 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='See',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Math ', 'Math'), ('Science', 'Science'), ('Social', 'Social'), ('Eph', 'Eph'), ('Account', 'Account'), ('Computer', 'Computer')], max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Years')),
            ],
        ),
        migrations.CreateModel(
            name='PlusTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('subjects', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Math', 'Math'), ('English', 'English'), ('Bio', 'Bio')], max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Years')),
            ],
        ),
    ]
