# Generated by Django 3.0.4 on 2020-03-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bachelors_year', models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV')], max_length=50)),
                ('question_year', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('CSIT', 'CSIT'), ('BIM', 'BIM'), ('BHM', 'BHM'), ('BCA', 'BCA'), ('BBA', 'BBA')], max_length=50)),
                ('semester', models.CharField(choices=[('First', 'I'), ('Second', 'II'), ('Third', 'III'), ('Fourth', 'IV'), ('Fifth', 'V'), ('Sixth', 'VI'), ('Seventh', 'VII'), ('Eighth', 'VIII')], max_length=50)),
                ('subjects', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
